name = "syanampro-v1"
main = "_worker.js"
compatibility_date = "2025-12-07"

[env.production]
name = "syanampro-v1"
routes = [
  { pattern = "syanam.pro/*", zone_name = "syanam.pro" }
]

[env.preview]
name = "syanampro-v1-preview"